[build]
publish = "website/build"
command = "pnpm run build:docs"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.deploy-preview]
ignore = "exit 0"
