packages:
  - 'packages/*'
  - 'plugins/*'
  - 'apps/*'
  - website
  - benchmark
  - '!tailwindcss-weapp'
  - '!**/test/**'
  # - "demo-linked/*"

catalogs:
  tailwindcss3:
    tailwindcss: ^3.4.17

  tailwindcss4:
    tailwindcss: ^4.0.12
