packages:
  - packages/*
  - plugins/*
  - apps/*
  - website
  - benchmark
  - '!tailwindcss-weapp'
  - '!**/test/**'
catalogs:
  tailwindcss3:
    tailwindcss: ^3.4.17
  tailwindcss4:
    tailwindcss: ^4.1.9
    tailwindcss4: npm:tailwindcss@^4.1.9
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
