# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
# base = "website/"
publish = "website/build"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
