name: Deploy Docs

on:
  # push:
  #   paths:
  #     - 'website/**'
  #   branches:
  #     - main
  workflow_dispatch:
  # repository_dispatch:
  #   types: [deploy_docs]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build:docs
      - name: Deploy
        run: pnpm run deploy
        working-directory: ./website
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        # uses: cloudflare/wrangler-action@v3
        # with:
        #   apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        #   accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        #   workingDirectory: ./website
        #   command: pages deploy .vitepress/dist --project-name=host-docs
